#define FUNCTION 0
#define RETURNS 1
#define VARS 2
#define FBEGIN 3
#define ENDFUNCTION 4
#define READ 5
#define WRITE 6
#define IF 7
#define THEN 8
#define ELSE 9
#define ENDIF 10
#define WHILE 11
#define LOOP 12
#define ENDLOOP 13
#define LT 14
#define LTE 15
#define EQ 16
#define NEQ 17
#define NUMBER 18
#define NAME 19
#define SEMI 20
#define COMMA 21
#define LBRA 22
#define RBRA 23
#define ASSIGN 24
